name: 🐳 Docker build & push

on:
  push:
    branches: [ 'main' ]
    paths:
      - '.github/workflows/genisoimage.build.yml'
      - 'genisoimage/*'
    tags:
      - '!*'
  pull_request:
    paths:
      - '.github/workflows/genisoimage.build.yml'
      - 'genisoimage/*'
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: genisoimage/.
          push: true
          tags: "tazorax/genisoimage:latest"
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: tazorax/genisoimage
          readme-filepath: ./genisoimage/README.md